### ISSUE TITLE
Lots of query execute warnings?

### ISSUE THREAD

**Issue by nzkfc** [overextended/oxmysql#112]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [x] I am using the latest release
- [x] I have referenced previously reported issues
- [x] I have referenced available documentation and cannot resolve the issue
- [] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
Running a server with 150-200 people, on startup and also during the server running we see lots of SQL queries warnings, If we have over 150 players, the server starts to drop clients and the thing falls over, if we bring it under 150 then it is fine-ish. I'm not 100% sure that it IS oxmysql, it could be a bad script (i.e qb-weed) or something, but i'm at a loss as to why this is happening.

Last year I ran a server that had 200-ish players and it was fine.

**Screenshots**
(This is if we drop the weed table and try run it)
https://i.imgur.com/CtfRuAy.png

(This is when we launch with the weed table populated)
https://i.imgur.com/8Y8BpjX.png

**Code**
N/A

**Expected behavior**
I guess, not as many warnings if all is working well?

**Additional context**
We have two dedi servers running on OVH (2x I7-7700k with 64GB+ memory and SSD's, we moved the server and SQL to the second one and the same issue occured.

We also have a dedi running a Xeon E3-1220v5 with 64GB and SSD's and the same thing happens, this box in particular was the one I ran an old city on in October last year that had 200+ pop.

I'm not too familiar with SQL so I have no idea how to troubleshoot if it's the SQL tables or a script or similar? Or if these querie response times are even normal.

**Server details**
- Latest recommended
- Windows 10 Pro (Xeon) and Windows Server 2019 (Intel i7)

**Database details**
- MariaDB
- 10.4.22

**Comment by thelindat** [comment]
Hitching and slow queries isn't unexpected on startup due to the extreme number of queries being executed at once.
Most resources aren't particularly optimised, and looking at qb-weed it could do with a lot of work with both queries and events.

> the server starts to drop clients and the thing falls over

That can happen during long server hitches, or with net event spam - you haven't really given information on what's happening when they disconnect, or what message they receive.


Run profiler on the server and configure your MySQL server settings if you haven't (just google). Ensure proper table indexes when a column is frequently used for WHERE in a query.

**Comment by nzkfc** [comment]
Thanks for the quick response mate.

I will get my guys at work to have a look at the above as im a bit of a potato when it comes to profiling and such. The guy at work did mention the constant queries in qb-weed didn't look healthy although said the table for plants was tiny in the grand scheme of things.

I might load the table into my old city and boot it and see also...
