### ISSUE TITLE
prepared statements

### ISSUE THREAD

**Issue by boermansjo** [overextended/oxmysql#113]
Just found this resource and looks very nice.
I still use the old mysql-async with the store function.

Does someone knows what advantages there are to use prepared statements over a stored one ?
I don't really see a way of doing the same with prepared statements in this script.
Plain mysql allows you to do
PREPARE stmt1 FROM 
	'SELECT * FROM users WHERE identifier = ?';
SET @user = playerIdentifier;
EXECUTE stmt1 USING @user;

The stored worked in a similar way. We only wrote the sql query once and used the stored name to run the query.
(Less traffic and all)

**Comment by thelindat** [comment]
mysql-async's store method literally just stored a string in an object, so you could send an id referencing that query; you simply get less serialisation when calling the query.

node-mysql2 will prepare and cache your statements for you when using the execute method - which we used _exclusively_, until we were basically forced to make the API 1:1 with mysql-async.

It's also important to note that mysql-async exclusively uses [COM_QUERY](https://dev.mysql.com/doc/internals/en/com-query.html) for text-based queries, which is vulnerable to SQL injection without proper parsing (see: esx_kashacter).

Using prepare will call [COM_STMT_PREPARE](https://dev.mysql.com/doc/internals/en/com-stmt-prepare.html) to cache and store the query internally, then [execute](https://dev.mysql.com/doc/internals/en/com-stmt-execute.html) it for that call and any future calls.

---

Stored procedures are also a thing and probably an even better choice since you can just do
```
MySQL.query(CALL PROCEDURE_NAME(arg1, arg2, ...))`
```

**Comment by boermansjo** [comment]
That is what I don't understand.
Using prepare should store the query in Mysql and later using the call name should be enough to execute the same query again.

But in the example of the documentation, it seems that you prepare the entire query again.
(https://overextended.github.io/docs/oxmysql/Usage/prepare)
(Or is the cache that intelligent to use a cached version ?)

I don't see where you use the statement-id created by the COM_STMT_PREPARE you mentioned.

(I am just checking how I can replace the stored ones using this more up-to-date version :) )

**Comment by thelindat** [comment]
https://github.com/sidorares/node-mysql2/blob/master/documentation/Prepared-Statements.md

This is all handled by node-mysql2 already by calling pool.execute

**Comment by boermansjo** [comment]
haha, yeah. I was just reading the documentation of the node-mysql2.
Was at the point of editing my comment with the link.

Seems clear enough now.
Thanks for the information.
