### ISSUE TITLE
No such export query in resource oxmysql No such export update in resource oxmysql [BUG?]

### ISSUE THREAD

**Issue by KinkyFivem** [overextended/oxmysql#136]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [ x] I am using the latest release
- [x ] I have referenced previously reported issues
- [x ] I have referenced available documentation and cannot resolve the issue
- [ x] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
it starts to send this errors qhen the server is fully loaded
No such export query in resource oxmysql
No such export update in resource oxmysql
**Screenshots**

![image](https://user-images.githubusercontent.com/109881773/181679714-61b2b16e-c55f-4f04-a1db-3a59254719da.png)

**Server details**
- 5744
- Windows

**Database details**
- MySQL
- Version

**Comment by thelindat** [comment]
😮‍💨 There are three possible causes, all attributed to user error (more specifically: user did not read).

1. Resource is calling an export _before_ oxmysql has started.
2. You are not running a production version (see: [release](https://github.com/overextended/oxmysql/releases/tag/v2.4.0)) or did not build the source code.
3. oxmysql encountered an error during startup (unlikely, but would show an error message higher in the console).

---

Option two is the most common scenario, since people either hit the big green "Code" button or go to the release and select the source code, instead of oxmysql.zip.
