### ISSUE TITLE
Query execute warnings

### ISSUE THREAD

**Issue by ClassEnkhbat** [overextended/oxmysql#180]
**Describe the bug**
I am having this spam query warnings. Is this needed to optimize database? This warnings still spamming when server less players. When it gets 100 players or more server just get laggy and players takes a long time to interact.

**Screenshots**
![warning2](https://github.com/overextended/oxmysql/assets/124324195/8ce6cd96-038e-44a6-aae8-b4bbd04f6cd5)
![warning1](https://github.com/overextended/oxmysql/assets/124324195/aa4e41b1-bf13-47f9-b426-03795455e2da)

**OxMysql versions**
- 2.6.0

**Server details**
- 6478
- Ubuntu 22.04
- Localhost (DB)

**Database details**
- MariaDB

**Comment by Griefa** [comment]
Sounds like you need to stop using a shitty framework like ESX

**Comment by davidxd33** [comment]
Your database/table design is unoptimized, server is slow, bad script design, or all of the above. Likely the fault of your server specs, or qs-* scripts more likely.

**Comment by ClassEnkhbat** [comment]
Its not qs- scripts. Any scripts that have databases are spamming like these. Is there any way to solve this?

**Comment by thelindat** [comment]
> Any scripts that have databases

They don't have databases, you have a database.

> spamming like these. Is there any way to solve this?

This is an issue with _your_ database and/or server hardware.

> When it gets 100 players or more server just get laggy and players takes a long time to interact.

Yes, it takes a long time to do things because.. 500ms query time is huge.

Note there's _also_ server thread hitches mixed in there, so the server is struggling and any queries executed before and resolved after a hitch will display higher times.

This is nothing to do with oxmysql.
