### ISSUE TITLE
Not possible way for custom transactions

### ISSUE THREAD

**Issue by kratess** [overextended/oxmysql#186]
## Issue checklist

- [x] I am using the latest release
- [x] I have referenced previously reported issues
- [x] I have referenced available documentation and cannot resolve the issue
- [x] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
  local response = MySQL.query.await([[
    START TRANSACTION;
    INSERT INTO users (identifier) VALUES ("identifier");
    SELECT * FROM users WHERE ID = LAST_INSERT_ID();
    COMMIT;
  ]], {})
  
Will go into error.

**Database details**
- MariaDB
- You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'INSERT INTO users (identifier) VALUES ("identifier");
- It works with phpmyadmin

**Comment by thelindat** [comment]
Won't work because [multi-statements](https://github.com/overextended/oxmysql/issues/102) are disabled to prevent easy SQL injection.

Use a stored procedure if it's that important to perform a single transaction, or just perform a second query using the result of the first.

**Comment by thelindat** [comment]
With multi-statements enabled:
![image](https://github.com/overextended/oxmysql/assets/65407488/4f1d2f55-43b2-4bc8-b7e2-506ab0a889d5)

Somewhat annoying results.

---

Returning a response from `MySQL.transaction` will just return the resultset for the `COMMIT` query, so I'd instead have to get each result and return those. Potentially breaking change and doesn't really match expected behaviour.

![image](https://github.com/overextended/oxmysql/assets/65407488/f3aeb0fa-b880-466c-8a6e-0a384b2a07c8)

---

Best solution is a stored procedure (as expected).

```lua
MySQL.transaction.await({
    'DROP PROCEDURE IF EXISTS `create_user`',
    [[
    CREATE PROCEDURE `create_user`(in identifier varchar(50))
    BEGIN
        INSERT INTO `users` (`license2`) VALUES (identifier);
        SELECT * FROM `users` WHERE `userid` = LAST_INSERT_ID();
    END
    ]]
})

local response = MySQL.query.await('CALL create_user("identifier")')

print(json.encode(response, {indent=true,sort_keys=true}))
```

![image](https://github.com/overextended/oxmysql/assets/65407488/499f0309-4345-430f-8905-64c0d9ca41c6

With the way results are handled, using `MySQL.scalar` will actually return the selected row here.

![image](https://github.com/overextended/oxmysql/assets/65407488/59c2db03-c86d-4163-9903-7c118d438a6d)
