### ISSUE TITLE
Mysql Slow Query Warning Problem

### ISSUE THREAD

**Issue by Botttiii** [overextended/oxmysql#193]
## Issue checklist
- [x] I am using the latest release
- [ ] I have referenced previously reported issues
- [x] I have referenced available documentation and cannot resolve the issue
- [x] I'm certain this is an issue with oxymysql, and not with my resource

**The mysql slow query warning not working with the new version, i just uploaded the new oxmysql version and there is the problem :D**

**Screenshots**
![image](https://github.com/overextended/oxmysql/assets/107773638/40fc5118-e6a4-4771-bd0d-60b54730639b)
![image](https://github.com/overextended/oxmysql/assets/107773638/b42731b6-cf9f-469d-a2a5-69b48976811e)

**Server details**
- v6.0.2 atop FXServer 6593
- Linux Debian 11

**Database details**
- MariaDB
-  10.5.19

**Comment by Botttiii** [comment]
Its done sry for this, but i don't know it will work fast and there is no slow query :D

**Comment by thelindat** [comment]
https://github.com/overextended/oxmysql/commit/45aadf744261a7d546635afaa6dc1a082cea06ad

Profiling is handled using mysql profiling rather than script-based. It's more accurate though adds some slight overhead; as such, it's only enabled if
- mysql_ui is enabled
- or mysql_debug is enabled globally
- or mysql_debug is an array and the invoking resource is included in the array
