### ISSUE TITLE
My database account and password are correct, why can't I connect to the database

### ISSUE THREAD

**Issue by jiahuo456** [overextended/oxmysql#219]
![1712327544-158624-image](https://github.com/overextended/oxmysql/assets/42507882/a5a92a9a-ee59-4562-a2cd-15ed09dc6d33)
![1712327583-821199-image](https://github.com/overextended/oxmysql/assets/42507882/245c7d4a-d31e-4d15-9eeb-7210ef03b8d5)
My database account and password are correct, why can't I connect to the database

**Comment by jiahuo456** [comment]
MariaDB

**Comment by thelindat** [comment]
Your console is reporting a template `{{dbConnectionString}}` from a recipe, rather than the value you're showing above (uhh, security?).

First correct that issue (you likely have multiple lines trying to set the convar), else refer to [this comment](https://github.com/overextended/oxmysql/issues/213#issuecomment-1980053775).
