### ISSUE TITLE
MySQL.update fsr stops code execution for a tick

### ISSUE THREAD

**Issue by mcNuggets1** [overextended/oxmysql#222]
## Issue checklist

**Describe the bug**
I used prints before and after MySQL.update and it actually took a tick to execute.
It halts the code for a full tick fsr. It shouldnt do that. Also I dont see it documented.

**Screenshots**

**Code**
```lua
	CreateThread(function()
		print(GetGameTimer())
		for i=1, 100 do
			MySQL.update("UPDATE owned_vehicles SET `stored` = 0 WHERE `owner` = @owner AND `plate` = @plate", {['@plate'] = "123", ['@owner'] = "123"})
		end

		print(GetGameTimer())
	end)
```

**Expected behavior**
https://i.imgur.com/kzwwSQY.png

**Additional context**

**Server details**
- FXServer artifact
- Operating system

**Database details**
- MariaDB or MySQL
- Version

**Comment by thelindat** [comment]
`GetGameTimer` gets the game time in milliseconds.
`MySQL.update` calls an export, and exports have a small amount of overhead.

You call the export 100 times, and it takes about 3ms; server ticks execute every 50ms.

**Comment by darksaid98** [comment]
Based on your testing we're talking ~0,03ms of execution time for every invocation which is pretty damn good.

What you really should be doing in a real-world scenario like this though, is using `MySQL.prepare`, which will allow you to *batch* execute the query multiple times for a dataset.

```lua
MySQL.prepare("UPDATE `owned_vehicles` SET `stored` = 0 WHERE `owner` = ? AND `plate` = ?", 
	{ -- Executes query once for each entry in this table
		{ 
			'Owner1', 'SOMEPLATE'
		},
		{
			'Owner3', 'SOMEPLATE'
		},
		{
			'Owner98', 'SOMEPLATE'
		},
		{
			'Owner5', 'SOMEPLATE'
		}
	}
)	

```

Granted, that isn't equivalent to your code, since it only executes 4 queries. However, it does avoid the overhead of calling the export multiple times.

There's a good benchmarking example for oxmysql in the docs here: https://overextended.dev/oxmysql/benchmark#script which is more precise than using `GetGameTimer`.
