### ISSUE TITLE
MySQL.Async is actually synchronous?

### ISSUE THREAD

**Issue by szajjch** [overextended/oxmysql#230]
So, I was recently going through your documentation, and I found a weird thing. Is MySQL.Async a synchronous statement? In your docs, you've got MySQL.Async.fetchAll which has allias: exports.oxmysql.query, but MySQL.Sync.fetchAll has allias: exports.oxmysql.query_async.

Is that just a typo, or there's actually a mistake in the code? Or I do not understand something?

![image](https://github.com/overextended/oxmysql/assets/45857590/d0e3848f-c354-4bb7-bb1c-7d9c3d0bbda9)

**Comment by thelindat** [comment]
Everything runs asynchronously, otherwise it would be blocking.

`MySQL.Async` is provided for backwards compatibility with https://github.com/brouznouf/fivem-mysql-async. The response is returned to a provided callback function.

`MySQL.Sync` is also provided for backwards compatibility. It called the exact same underlying function and returned to a predefined callback function that would call `Wait` every tick (50ms) until a response was received.

https://github.com/brouznouf/fivem-mysql-async/blob/master/lib/MySQL.lua#L48-L59

It works pretty much the exact same for oxmysql, except it uses promises instead of checking every 50ms. The exports suffixed with `_async` return an "async retval" which is wrapped into a promise (and in the case of Lua, automatically awaited).

**Comment by szajjch** [comment]
Thanks for explaining.
