### ISSUE TITLE
MySQL connections

### ISSUE THREAD

**Issue by nzodevfivem** [overextended/oxmysql#246]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [x] I am using the latest release
- [x] I have referenced previously reported issues
- [x] I have referenced available documentation and cannot resolve the issue
- [x] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**

My MySQL database does not connect with oxmysql. It does not contact the right IP and refuses the connection. And the connection works without problem with mysql-async except that I need oxmysql

**Screenshots**
![IMG_20241017_071937](https://github.com/user-attachments/assets/26532b5c-93d6-42c6-a436-a4c0ac40d986)
We can clearly see that my IP is 89.213.X.X and he tries to connect to 172.18.X.X

**Server details**
- FXServer artifact (latest)
- Operating system

**Database details**
- MariaDB or MySQL (MySQL, phpmyadmin)
- Version

**Comment by thelindat** [comment]
172.18.X.X is a private address and just the resolved address from your public ip because your database is on the same network.
If there were no database at the address you wouldn't be getting access denied error.

As always ensure your password doesn't use reserved characters or swap to the other connection string format (why do I even have docs or common issues listed sigh).
