### ISSUE TITLE
Table creation fails

### ISSUE THREAD

**Issue by LouisMylle** [overextended/oxmysql#66]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [X] I am using the latest release
- [X] I have referenced previously reported issues
- [X] I have referenced available documentation and cannot resolve the issue
- [ ] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
I installed the plugins as it should. vRP is trying to create the necessary tables using oxmysql. I can't get it to work. I tried MySQL, MariaDB, different MySQL authentication modes, ... Don't know for sure if this is a problem with oxmysql or just me doing something wrong. 

**Screenshots**
![Schermafbeelding 2021-11-17 om 00 04 42](https://user-images.githubusercontent.com/53264639/142080303-de37d898-a2fe-4e88-b8c9-896bae226cd7.png)

**Server details**
- FX Server artifact: latest version
- Operating system: alpine (ran in docker container on pterodactyl) 
- Framework: vRP

**Comment by LouisMylle** [comment]
Thanks in advance for any help. Regards, Louis Mylle.

**Comment by dunak-debug** [comment]
So as I see you are executing multiple queries at once. This is disabled by default within `node-mysql2` and shouldn't be enabled because:

> Support for multiple statements is disabled for security reasons (it allows for SQL injection attacks if values are not properly escaped).

**Comment by LouisMylle** [comment]
Hi Dunak,

Thanks for your fast response. Didn’t know about multiple queries.. 

When I run the queries in phpmyadmin of mysqlworkbench they do work indeed. 

Regards,
Louis

**Comment by dunak-debug** [comment]
Can you run them separately?

**Comment by darksaid98** [comment]
Passing multiple queries is not supported in oxmysql.

This was previously touched upon in multiple issues, most prominently in #35 where we also mentioned that you can enable this for yourself. Please note that if you do not understand the security implications of enabling this, you probably shouldn't be toggling it.

 @dunak-debug, @thelindat I'm out of the loop on what you gents have planned for 2.0.0, but maybe some export that can be used for DB setup/creation. Since oxmysql is what I'd call an eco-system critical resource we might even want Bubbles input on such since it opens the way for malicious scripts to just drop DBs.
