### ISSUE TITLE
oxMySQL does not support Pterodactyl servers.

### ISSUE THREAD

**Issue by venimo** [overextended/oxmysql#83]
When using OXMySQL on a Pterodactyl server, the IP placed inside the server.cfg is totally changed to example: 172.18.0.3 that IP is nerver shown on any server file before.

How you get it:

1) Have a server on Pterodactyl.
2) Have an IP in your mysql connection string (for example 1.2.3.4)
3) Start your server
4) Now you see the following error in your console: Access denied for user 'username'@'172.18.0.3' (using password: YES)

As you see the IP changed, and the IP is nerver found in all of my server files, nor hosting company knows where it's from.

**Comment by darksaid98** [comment]
I can't reproduce this with either `mysql_connection_string` formats which seem to rule out parser issues. 

> nor hosting company knows where it's from

I can see they didn't contact their sys-admins. In this Pterodactyl-specific case, `172.18.0.3` is your container's (**servers**) internal address.

**I have one question.** Are you attempting to connect to a local DB using `localhost` in the connection string?

> If you are attempting to connect to a local DB and you are using `localhost` then may I suggest trying `172.18.0.1` or `172.17.0.1` instead.

If not. Then we're kind of stuck since the bug you described cannot be reproduced by me on v1.9.3 on either Pterodactyl or Windows.

**Comment by darksaid98** [comment]
No response from OP. Closing this.
