### ISSUE TITLE
timeout warning spam

### ISSUE THREAD

**Issue by nerohiro** [overextended/oxmysql#88]
## Issue checklist
> Please put `x` inside of the box that matches your issue.

- [x] I am using the latest release
- [x] I have referenced previously reported issues
- [x] I have referenced available documentation and cannot resolve the issue
- [x] I'm certain this is an issue with oxymysql, and not with my resource

**Describe the bug**
if a server takes a long period of time to start, it will timeout, which is normally fine but since the latest release it will continue to spam it until you restart oxmysql, im not quite sure if it effects any server in a negative way besides just annoying the person looking at the server log, but im sure whoever works on oxmysql will be able to find out

**Screenshots**
https://lobfile.com/file/rWRi.png
https://media.discordapp.net/attachments/887464412603093035/944684154577109012/unknown.png
https://lobfile.com/file/uU6w.png

**Expected behavior**

not to spam the server log, maybe attempt to connect again after timing out

**Server details**
oxmysql v2.0.1
artifact 5327
windows server, windows 10 (happens on local servers too)

**Database details**
MariaDB

**Comment by LukeWasTakenn** [comment]
This *spam* is by design, it happens when your database isn't properly connected
https://github.com/overextended/oxmysql/blob/9cb22df2fd10a38fdb423dde3eec4cdc047d63ff/src/database/index.ts#L15-L18

In most cases this appears to be an issue when starting oxmysql before starting your custom assets that that a long time to load such as vehicles, weapons, peds, etc...
